### ISSUE TITLE
Make initramfs compression method optional

### ISSUE THREAD

**Issue by RefinedAnarchy** [TheGreatMcPain/buildkernel-dracut#2]
Right now, its either no compression or XZ compression in /etc/buildkernel.conf. There should be an option for other compression methods like lz4, zstd, lzo, etc...

**Comment by TheGreatMcPain** [comment]
Sorry for taking this long to respond.  I don't check this repository much, and the emails got buried.

I've made [this commit](https://github.com/TheGreatMcPain/buildkernel-dracut/commit/33e587e3a7131a609b7dd83bbc429da31b88e2ae), which is included in the newest release, last year which should satisfy your request.
